### ISSUE TITLE
Variance changes when fixed parameters are included in model

### ISSUE THREAD

**Issue by tokamage** [tBuLi/symfit#212]
Including fixed parameters in models breaks the calcuation of covariances and therefore variances for the free parameters. As an example, using the code and values in the first section of the docs:

```
a, b = sf.parameters('a, b')
x, y = sf.variables('x, y')
model = sf.Model({y: a * x + b})
```
**gives**
parameter values: [1.100, 1.080]
parameter variances: [0.001, 0.011]

**Adding**
```
c= sf.Parameter('c',value=1,fixed=True)
new_model = sf.Model({y: a * x + c * b})
```
**gives**
parameter values: [1.100, 1.080, 1]
parameter variances: [0.001, -6333186976592.431, -5429687050228.977]

**Comment by pckroon** [comment]
Great find, thanks!
@tBuLi We calculate the covariance matrix by inverting the Hessian of the objective (https://github.com/tBuLi/symfit/blob/master/symfit/core/fit.py#L993). So to fix this we would have to exclude the fixed parameters from the hessian? That sounds weird to me. In addition, what happens if they're not fixed to 1?

**Comment by tBuLi** [comment]
Thanks for this report, that's a weird one. @pckroon In the current release I don't think we invert the Hessian yet, although that is a change which is included in #201 if I remember correctly. So I think we should look at this issue again after that has been merged, because it might solve the problem immediately.

As for what we expect the covariance of a fixed parameter to be, there are two different answers the way I see it. The first, which is the implementation if we invert the Hessian of the objective, is simply zero since it doesn't vary and is seen as a constant number in this regard. The second might be that you are interested in what would've been the variance in `c`, had it been a non-fixed parameter which happens to be `1` in this example.

But I think the first is the right answer for symfit to give, and if someone needs the second they can always manually evaluate the objective at that point again, but now with `c` no longer fixed so the Hessian becomes 3x3 instead of 2x2, and invert that instead.

**Comment by pckroon** [comment]
> Thanks for this report, that's a weird one. @pckroon In the current release I don't think we invert the Hessian yet, although that is a change which is included in #201 if I remember correctly. So I think we should look at this issue again after that has been merged, because it might solve the problem immediately.

It's already in master.

The variance of a fixed parameter should be 0 I think. However, in the original example the really interesting case is the variance of `b`. In addition, the co-variance between `b` and `c` is something I don't know. And how does the variance of `b` and the covariance `b-c` change with the value of `c` (which is fixed)?
These questions also reveal my issues regarding inverting the 2x2 Hessian: how do we then deal with the covariances?

**Comment by tBuLi** [comment]
#195 only introduced this for LogLikelihood, not for regular least squares fitting. So there is still hope that this problem will be magically fixed.

And then we are in agreement that a variance of 0 is desired since it is essentially a constant. So this also means that there is no covariance in the term `b * c` in this case, `c` is treated as just a constant. Since there is no covariance nor variance, we can safely invert the 2x2 matrix, and add rows and columns of zeros for c in order to make a 3x3. We should check if this is done properly before sending the result into a `FitResults` object.

**Comment by pckroon** [comment]
Ah yes, I read the code too fast. Then indeed I think we might have a workable solution. Could you prototype and test the 3x3 hessian inversion, and the 2x2 H inversion real quick before we fully implement it? I'm utterly swamped.

**Comment by tokamage** [comment]
Using the code on master after #201 was merged the issue still persists. To make sure I'm using the correct version, should symfit.__version__ be '0.4.7.dev118'?

**Comment by tBuLi** [comment]
Thanks for keeping track of this. I tried your example again after merging and indeed the variance of `b` and `c` stays ridiculously large. However, after thinking about it some more, I do think that the result is correct.  Because lets say that we know that `b * c = 1`. Then there are infinitely many choices for `b` and `c` which still give `b*c = 1`. This results in a large standard deviation. So I think the result you are currently getting is in fact correct.

The problem is more in the philosophical meaning of a `fixed` Parameter, about which @pckroon and I currently have a difference of opinion. (And I with my past self actually, reading back to what I wrote above.) The essence is this: is a fixed parameter the same as a constant? My past self and pckroon think yes, my current self thinks no.

The way I now see it, adding a Parameter adds an extra dimension to the parameter space. You can then select a subspace of that by fixing a parameter, but that does not mean that the extra dimension is not there. Covariances are sensitive to this extra dimension, and will therefore be different from what you would get if you actually used a constant. E.g.
```python
c = sf.Parameter('c', value=2, fixed=True)
new_model = sf.Model({y: a * x + c * b})
```
is not the same as ```new_model = sf.Model({y: a * x + 2 * b})```.

So I'm currently erring on the side of wont-fix, because I think this is the correct behavior, but I can still be swayed by good arguments.

p.s. sympy substitution allows you to dynamically replace a symbol and would be the way to get the behavior you expect, e.g.
```python
expr = a * x + c * b
new_model = sf.Model({y: expr.subs(c, 2)})
```

**Comment by pckroon** [comment]
I'm still unsure on what the desired behaviour here is. The main question is this: Is a parameter with infinitely tight bounds the same as a constant? I don't really have an answer to that, and I think it's a matter of definition. Either way, it has to go into the docs with big, bold (and possibly blinking) letters.

This also segways nicely into the question how bounds (should) influence (co)variances.

**Comment by tokamage** [comment]
Maybe we can reach a better understanding by considering several questions: 
1) What is the purpose of a fixed parameter? Does it differ from a constant only by producing a difficult to understand variance in the model? If so, in which case would I want to use it?
2) What is meant by bounds? Are they simply guides for the optimiser or flat priors like in baysian statistics? If the bounds represent some knowledge about the parameters, what does a variance outside of the bounds mean?
 
My Answer to 1) would be that fixed paramters give practical flexibility to a model that might not be used at the time. They remind the user when looking at model.params that some human choice has been made, unlike multiplication by constants which may be dictated by nature (such as unit conversion). For this reason I would propose to keep using fixed paramters, but disregard them in the calculation of covariances. 

To 2) I don't have an answer, but it seems to me like there are two options. Bounds are just for the optimiser, the 'math' of the model doesn't know about them: Variances can exceed bounds. Smaller bounds shouldn't affect the mean (if it's within them) or variance of a parameter. If a parameter is ill specified by the model the variance increases, until at the extreme case of a*b=1 it reaches infinity. 
OR Bounds reflect our knowledge of a parameter: (e.g.: A temperature can't be below 0.) Variances can however still exceed bounds because they are a symmetric moment of the potentially asymmetric distribution (Fig.1). If we know a parameter has a certain value it's distribution is a delta peak, it's variance is 0. A paramter with tight bounds might be equally likely at each point within them, to show this the variance would be very wide (Fig.2).
I don't really know how option one would be implemented and it would certainly have to be highlighted in the documentation. Option two seems intuitive and easy to implement.
I've drawn some Figures to help myself understand and illustrate my point:
[ParameterBounds.pdf](https://github.com/tBuLi/symfit/files/3002590/ParameterBounds.pdf)

**Comment by pckroon** [comment]
Thanks for the extensive write-up, this is incredible valuable to us since neither of us (and me in particular) really know statistics.

I'll comment on 2) first, since that looks easier at the moment.
2b) seems self-contradictory: as bounds get tighter the variance goes up, until `lower_bound == upper_bound`, at which point the variance should become 0.
I think that at the moment we have 2a) implemented, which you see when you fix a parameter: the covariance is not affected by the bounds, only by the model. (The only difference from what you describe is that tight bounds *can* influence the mean in e.g. SLSQP due to how it's implemented)
I also don't really see how you would implement 2b), just sample 100 points in the hyper-rectangle spanned by your parameter bounds? What if some don't have bounds? We do 2a) by deriving and inverting the Hessian.
Lastly on 2): I think option 2a) is also preferred since that is what is "expected". Compatibility with existing fitting software is important. Some deviations due to implementation (invert Hessian vs first order approximation J*J.T) are fine, but we can't really change the definition of what a (co)variance means.

As to 1): I see both cases being useful (as a constant, and as a parameter with infinitely tight bounds). So maybe we should add a `Constant` object alongside `Variable` and `Parameter`?

**Comment by tokamage** [comment]
Your welcome, your package is incredibly valuable to me so I'm happy to help!

> 2b) seems self-contradictory: as bounds get tighter the variance goes up, until `lower_bound == upper_bound`, at which point the variance should become 0.
I thought some more about it and spoke with a colleague, it appears I mixed up some things. It is contradictory because it is wrong which is what causes this problem in the first place! 
My argument was supposing that the quality value of points outside the bounds were extrapolated from those within. In that case a flat distribution of points within would be extrapolated to a flat distribution outside. The derivative of this flat distribution is small, hence the hessian finds a large variance. But the quality of points outside the bounds is 0! Continuing my example from above, we know T>=0. So the derivative at the bound is actually very steep and the variance therefore small, as expected. For a constant the derivative with the surrounding zeros is infinite, so the variance is 0.
Furthermore statistically variance is defined as sigma=SUM_i_to_N ( ( x_i - mu )^2 / N ). So as the bounds get tighter the variance decreases until for a constant c, x_i = c = mu and sigma = 0. 

> As to 1): I see both cases being useful (as a constant, and as a parameter with infinitely tight bounds). So maybe we should add a `Constant` object alongside `Variable` and `Parameter`?
That's certainly a possibility, but I can't think of a use for fixed parameters as they currently work. Isn't it much nicer to have a (possibly complicated, multi-parameter model) and gradually 'switch on' more fitting dimensions by changing the 'fixed' property rather than switching to a different type each time?

[ParameterBounds2.pdf](https://github.com/tBuLi/symfit/files/3004227/ParameterBounds2.pdf)

**Comment by pckroon** [comment]
Thanks. You almost have me convinced :)

I think it'll boil down to the following 2 questions:
1) What is the expected behaviour?
2) Why do we provide the option to fix parameters?

Where the answer to 1) strongly depends on the answer to 2).

In addition, I think we can also leave bounds out of consideration for this, because we evaluate the Hessian *exactly at* the solution, and that solution is guaranteed to be within the bounds. By the same reasoning the value of the Hessian at the bounds is irrelevant. The only special case is where parameter are fixed, and the solution *is* the bounds.

Constants are indeed not useful. They add nothing over a simple float variable.

**Comment by tokamage** [comment]
Have you found an answer to your questions? 
To me it seems pretty clear that, as you state:
- Constants are not a usefull object.
- Therefore fixed parameters are there to temporarily disable parts of the model while keeping the structure the same.
- Therefore they should **behave** like constants and be not considered in the variance calculation, but they should be **accounted** for as parameters and listed in model.params

**Comment by tBuLi** [comment]
I agree with the first two points of your summary. Fixing of parameters is solely there to temporarily disable a parameter, or in a way to force it to have a certain value. However, whether or not it is included in the covariance matrix does not stop it from fulfilling that particular role.

Something I find very clear about the current behavior is that it forces the user to think about the result they got. This is also the case for some of your earlier points about whether variances should respect certain pre-knowledge about our parameters. I'm not sure that they should, I would much rather force users to rethink what they are doing and calculate it themselves, than to risk people taking the values at face value without thinking about what applies to their situation.

However, what is very clear from this discussion is that the term `fixed` is ambiguous. What we could consider is to introduce a keyword `constant` or even `as_constant` if it really should be treated as such, and to set the `min` and `max` bound identical to create a fixed parameter as in my interpretation. This is also more in line with forcing users to think :P.

As an additional difficulty, I recently discovered that Parameters should be immutable, because that's what SymPy expects. Therefore, their API needs to be rethought significantly.

For now, I think we should leave this behavior as it is, but for a version 0.6.0 these ideas need to be addressed.
