### ISSUE TITLE
No compatible with numpy 1.24.1

### ISSUE THREAD

**Issue by stephanlachnit** [tBuLi/symfit#363]
Reported originally [here](https://bugs.debian.org/1027245).

The expired deprecation are listed [here](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations).

**Comment by pckroon** [comment]
Thanks for reporting this. As far as I can see this has already been fixed in #342 via 1b683233d1e0c2ced5e96c9630fd3aeb22ca982c

**Comment by stephanlachnit** [comment]
> Thanks for reporting this. As far as I can see this has already been fixed in #342 via [1b68323](https://github.com/tBuLi/symfit/commit/1b683233d1e0c2ced5e96c9630fd3aeb22ca982c)

Ah good to know, thanks! Can you tag a new release with this?

**Comment by pckroon** [comment]
@tBuLi ?

**Comment by tBuLi** [comment]
Thanks for your help. I will tag a new release ASAP, although I would also like to merge #365 first, because that also represents a significant but straightforward clean-up of the code base. So I expect a new release will be made by the end of the week.

**Comment by tBuLi** [comment]
I just made a new release. But looking back on this discussion something seems off to me: #342 was already merged and present in earlier releases. So it seems to me that this issue might still exist?

**Comment by pckroon** [comment]
When I looked I couldn't find the changes made in that PR in the latest release. I also couldn't reproduce the original issue on the main branch.

@stephanlachnit Can you confirm this is fixed in yesterday's release?

**Comment by stephanlachnit** [comment]
> @stephanlachnit Can you confirm this is fixed in yesterday's release?

Seems to be fixed, closing.

**Comment by pckroon** [comment]
Great! Thanks again for reporting this, and thanks for reporting back
